// Migración v007: agrega met_value a exercise y estimated_calories a training_session
// MET (Metabolic Equivalent of Task): unidad que expresa el costo energético de una actividad
// Calorías ≈ MET × peso_kg × horas_de_ejercicio × factor_RPE
import { Migration } from '../../services/migrationService';

export const v007_met_calories: Migration = {
  version: 7,
  name: 'v007_met_calories',
  up: [
    // Valor MET por ejercicio — default 7 (actividad moderada-alta genérica)
    `ALTER TABLE exercise ADD COLUMN met_value REAL DEFAULT 7.0`,

    // Calorías estimadas calculadas al finalizar cada sesión
    `ALTER TABLE training_session ADD COLUMN estimated_calories INTEGER`,

    // ── Valores MET para ejercicios conocidos ──────────────────────────────
    // MET muy alto (12–14): WOD/AMRAP, ejercicios de alta potencia
    `UPDATE exercise SET met_value = 14.0 WHERE name = 'Burpee'`,
    `UPDATE exercise SET met_value = 14.0 WHERE name = 'Bodyweight Burpee'`,
    `UPDATE exercise SET met_value = 13.0 WHERE name = 'Double Under'`,
    `UPDATE exercise SET met_value = 13.5 WHERE name = 'Burpee Over the Bar'`,
    `UPDATE exercise SET met_value = 12.0 WHERE name = 'Assault Bike'`,
    `UPDATE exercise SET met_value = 12.0 WHERE name = 'Bar Muscle-Up'`,
    `UPDATE exercise SET met_value = 12.0 WHERE name = 'Ring Strict Muscle Up'`,

    // MET alto (10–12): cardio, saltos, movimientos explosivos
    `UPDATE exercise SET met_value = 11.0 WHERE name = 'Running'`,
    `UPDATE exercise SET met_value = 11.0 WHERE name = 'Shuttle Run'`,
    `UPDATE exercise SET met_value = 10.0 WHERE name = 'Rowing'`,
    `UPDATE exercise SET met_value = 10.5 WHERE name = 'Box Jump'`,
    `UPDATE exercise SET met_value = 10.5 WHERE name = 'Box Jump-Over'`,
    `UPDATE exercise SET met_value = 10.0 WHERE name = 'Wall Walk'`,
    `UPDATE exercise SET met_value = 10.0 WHERE name = 'Rope Climb'`,
    `UPDATE exercise SET met_value = 10.0 WHERE name = 'Toes to Bar (T2B)'`,
    `UPDATE exercise SET met_value = 10.0 WHERE name = 'Hanging Toes to Bar'`,

    // MET moderado-alto (8–10): levantamientos olímpicos, movimientos complejos
    `UPDATE exercise SET met_value = 9.5 WHERE name = 'Thruster'`,
    `UPDATE exercise SET met_value = 9.5 WHERE name = 'Barbell Thruster'`,
    `UPDATE exercise SET met_value = 9.5 WHERE name = 'Dumbbell Thruster'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Clean & Jerk'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Barbell Clean and Jerk'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Barbell Hang Clean and Jerk'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Kettlebell Clean and Jerk'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Snatch'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Barbell Power Snatch'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Barbell Muscle Snatch'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Barbell Hang Power Snatch'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Kettlebell Snatch'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Power Clean'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Barbell Hang Power Clean'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Barbell Squat Clean'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Barbell Hang Clean'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Wall Ball Shot'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Kettlebell Swing'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Kettlebell Sumo Deadlift High Pull'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = 'Barbell Sumo Deadlift High Pull'`,
    `UPDATE exercise SET met_value = 9.0 WHERE name = "Farmer's Carry"`,
    `UPDATE exercise SET met_value = 8.5 WHERE name = 'Chest-to-Bar Pull-Up'`,
    `UPDATE exercise SET met_value = 8.5 WHERE name = 'Pull-up'`,
    `UPDATE exercise SET met_value = 8.5 WHERE name = 'Bar Pull Up'`,
    `UPDATE exercise SET met_value = 8.5 WHERE name = 'Kettlebell Ground-to-Overhead'`,
    `UPDATE exercise SET met_value = 8.5 WHERE name = 'Alternating Single Arm Dumbbell Power Snatch'`,
    `UPDATE exercise SET met_value = 8.0 WHERE name = 'Dumbbell Split Clean'`,
    `UPDATE exercise SET met_value = 8.0 WHERE name = "Dumbbell Devil's Press"`,

    // MET moderado (6–8): fuerza, sentadillas, press
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Deadlift'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Barbell Deadlift'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Barbell Romanian Deadlift'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Nordic Hamstring Curl'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Single-Leg Dumbbell Romanian Deadlift'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Air Squat'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Bodyweight Squat'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Back Squat'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Barbell Back Squat'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Front Squat'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Barbell Front Squat'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Overhead Squat'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Barbell Overhead Squat'`,
    `UPDATE exercise SET met_value = 7.5 WHERE name = 'Bodyweight Pistol Squat'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Push Press'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Barbell Push Press'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Barbell Push Jerk'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Barbell Strict Press'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Shoulder Press'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Barbell Hang Muscle Clean and Press'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Push-up'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Bodyweight Push Up'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Kettlebell Push-Up'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Ring Dip'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Dips'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Bodyweight Handstand Push-Up'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Ring Handstand Push-Up'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Walking Lunge'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Bodyweight Walking Lunge'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Barbell Lunge'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Dumbbell Front Rack Lunge'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Dumbbell One-Arm Overhead Lunge'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Double Dumbbell Overhead Walking Lunge'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Weighted Box Step-Up'`,
    `UPDATE exercise SET met_value = 7.0 WHERE name = 'Med-Ball Box Step-Over'`,
    `UPDATE exercise SET met_value = 6.5 WHERE name = 'Barbell Bench Press'`,
    `UPDATE exercise SET met_value = 6.5 WHERE name = 'Dumbbell Bench Press'`,
    `UPDATE exercise SET met_value = 6.5 WHERE name = 'Barbell Bent Over Row'`,
    `UPDATE exercise SET met_value = 6.5 WHERE name = 'Barbell Upright Row'`,
    `UPDATE exercise SET met_value = 6.5 WHERE name = 'Dumbbell Alternating Bent Over Row'`,
    `UPDATE exercise SET met_value = 6.5 WHERE name = 'Dumbbell Bicep Curl'`,
    `UPDATE exercise SET met_value = 6.5 WHERE name = 'Dumbbell Front Raise'`,
    `UPDATE exercise SET met_value = 6.5 WHERE name = 'Bent-Over Dumbbell Lateral Raise'`,
    `UPDATE exercise SET met_value = 6.5 WHERE name = 'Ring Row'`,
    `UPDATE exercise SET met_value = 6.5 WHERE name = 'GHD Back Extension'`,
    `UPDATE exercise SET met_value = 6.0 WHERE name = 'Barbell Hang Power Cluster'`,
    `UPDATE exercise SET met_value = 6.0 WHERE name = 'Kettlebell Front Squat'`,

    // MET bajo-moderado (4–6): core, estabilidad, movilidad
    `UPDATE exercise SET met_value = 5.5 WHERE name = 'GHD Sit-Up'`,
    `UPDATE exercise SET met_value = 5.5 WHERE name = 'Bodyweight Sit Up'`,
    `UPDATE exercise SET met_value = 5.5 WHERE name = 'Toe Touch Sit-Up'`,
    `UPDATE exercise SET met_value = 5.5 WHERE name = 'Stability Ball Plate Crunch'`,
    `UPDATE exercise SET met_value = 5.0 WHERE name = 'Toes to Bar (T2B)'`,
    `UPDATE exercise SET met_value = 5.0 WHERE name = 'Hanging Knees to Elbows'`,
    `UPDATE exercise SET met_value = 5.0 WHERE name = 'Russian Twist'`,
    `UPDATE exercise SET met_value = 5.0 WHERE name = 'Hollow Hold'`,
    `UPDATE exercise SET met_value = 5.0 WHERE name = 'Bodyweight Hollow Body Hold'`,
    `UPDATE exercise SET met_value = 5.0 WHERE name = 'Hollow Rock'`,
    `UPDATE exercise SET met_value = 5.0 WHERE name = 'Hollow to Superman Roll'`,
    `UPDATE exercise SET met_value = 4.5 WHERE name = 'Plank to Opposite Toe Touch'`,
    `UPDATE exercise SET met_value = 4.5 WHERE name = 'Bodyweight Glute Bridge'`,
    `UPDATE exercise SET met_value = 4.0 WHERE name = 'Superband Shoulder Dislocates'`,
  ],
  down: [],
};
